name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
    - name: Test Lua 5.1 yyyy
      working-directory: ${{runner.workspace}}/build/Tests
      shell: bash
      run: ls -la
    - name: Test Lua 5.1 xxxx
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ls -la
    - name: Test Lua 5.2
      working-directory: ${{runner.workspace}}/build/Tests
      shell: bash
      run: LuaBridgeTests52
    - name: Test Lua 5.3
      working-directory: ${{runner.workspace}}/build/Tests
      shell: bash
      run: LuaBridgeTests53
    - name: Test Lua 5.4
      working-directory: ${{runner.workspace}}/build/Tests
      shell: bash
      run: LuaBridgeTests54

  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
    - name: Test Lua 5.1
      working-directory: ${{runner.workspace}}/build/Tests/$BUILD_TYPE
      shell: bash
      run: ./LuaBridgeTests51
    - name: Test Lua 5.2
      working-directory: ${{runner.workspace}}/build/Tests/$BUILD_TYPE
      shell: bash
      run: ./LuaBridgeTests52
    - name: Test Lua 5.3
      working-directory: ${{runner.workspace}}/build/Tests/$BUILD_TYPE
      shell: bash
      run: ./LuaBridgeTests53
    - name: Test Lua 5.4
      working-directory: ${{runner.workspace}}/build/Tests/$BUILD_TYPE
      shell: bash
      run: ./LuaBridgeTests54

  macos_build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE
    - name: Test Lua 5.1
      working-directory: ${{runner.workspace}}/build/Tests
      shell: bash
      run: ls -la
    - name: Test Lua 5.2
      working-directory: ${{runner.workspace}}/build/Tests
      shell: bash
      run: ./LuaBridgeTests52
    - name: Test Lua 5.3
      working-directory: ${{runner.workspace}}/build/Tests
      shell: bash
      run: ./LuaBridgeTests53
    - name: Test Lua 5.4
      working-directory: ${{runner.workspace}}/build/Tests
      shell: bash
      run: ./LuaBridgeTests54
